apiVersion: v1
data:
  ack-4.16-flowschemas-removal: "true"
  ack-4.16-prioritylevelconfigurations-removal: "true"
  ack-4.15-kube-1.29-api-removals-in-4.16: "true"
kind: ConfigMap
metadata:
  name: admin-acks
  namespace: openshift-config
